### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by Moocow9m** [ekaomk/Minecraft-RCON-Console#1]
Takes too much memory

12/5/2015 @ 21:25:8 <- 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 758133299 bytes) in Z:\xampp\htdocs\rcon\rcon.php on line 157

**Comment by ekaomk** [comment]
rcon.php (RCON Library) owned by Chris Churchwell http://chrischurchwell.com/query-rcon-classes-for-php/ 
fast way to fix this problem. try to set max allocate memory with "ini_set" command and upgrade php to last version.

**Comment by Moocow9m** [comment]
thanks will try that. Could you put that into your readme.md or somewhere in a text document when I recommend this because some people don't know that because not many people have that much memory to spare to send a simple save-all command.
