### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by Moocow9m** [ekaomk/Minecraft-RCON-Console#2]
said sent successful but the server never responded!
Send success!
Console
Welcome to Minecraft RCON Console.
View all command at http://minecraft.gamepedia.com/Commands.
View item name and id at http://www.minecraftinfo.com/idlist.htm
13/5/2015 @ 15:42:18 -> save-all
13/5/2015 @ 15:42:18 <-

Game Type : SMP
Version : 1.8.3

**Comment by ekaomk** [comment]
Read the README.md on Setting up section. https://github.com/ekaomk/Minecraft-RCON-Console/blob/master/README.md#setting-up

I think your server configuration is not correctly.

**Comment by Moocow9m** [comment]
Server is confiqured correctly.

**Comment by ekaomk** [comment]
try to post request to /rcon/index.php by send "cmd" parameter with command. then post the result in here.

i recommend chrome extension named "POSTMAN" to do that.
https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by Moocow9m** [comment]
cant install chrome apps because avast won't let me. so if you could recommend something else?

**Comment by ekaomk** [comment]
HTTP Test Tool
http://sourceforge.net/projects/htt/
